version: '3.7'
services:
  # web:
  #   build: ./src/FrontEnd
  #   environment:
  #     - REACT_APP_INSTRUMENTATION_KEY
  #     - REACT_APP_AUTH_CLIENT_ID
  #     - REACT_APP_SEPES_BASE_URL
  #   ports:
  #     - target: 8080
  #       published: 8080
  #       protocol: tcp
  #       mode: host
  restapi:
    build: ./src
    environment:
      - SEPES_Appi_Key=881d305a-4b34-4f3d-8919-dbaad1ab8885
      - SEPES_HttpOnly=true
      - ClientId=e90cbb61-896e-4ec7-aa37-23511700e1ed
      - ClientSecret=WQ-1xb89o~Nv-n6kIJ4vM8O.4~~08cxNAz
      - KeyVault_Url=https://kv-sepes-dev.vault.azure.net/
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host