apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: sepes
spec:
  environments:
    - name: dev
      build:
        from: develop
    - name: prod
      build:
        from: master
  components:
    - name: frontend
      src: src/FrontEnd
      ports:
        - name: http
          port: 80
      publicPort: http
      environmentConfig:
        - environment: prod          
          monitoring: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
    - name: backend
      src: src/BackEnd
      ports:
        - name: http
          port: 5001
      environmentConfig:
        - environment: dev
          variables:
        - environment: prod
          replicas: 2
          variables: 
            SEPES_NAME: "radix-sepes-dev"
            SEPES_TENANT_ID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            SEPES_SUBSCRIPTION_ID: "6cfb8f33-6d4b-43bf-9000-91fd6f53ca28"
            SEPES_HTTP_ONLY: false
            SEPES_JOIN_NETWORK_ROLE_NAME: hmh
      secrets:
        - SEPES_KEYVAULT_URL
        - SEPES_CLIENT_ID
        - SEPES_CLIENT_SECRET
        - SEPES_INSTRUMENTATION_KEY
        - SEPES_MSSQL_CONNECTION_STRING
  dnsAppAlias:
    environment: prod
    component: frontend
  dnsExternalAlias:
