apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: sepes
spec:
  environments:
    - name: dev
      build:
        from: develop
    - name: prod
      build:
        from: master
  components:
    - name: frontend
      src: src/FrontEnd
      ports:
        - name: http
          port: 80
      publicPort: http
      environmentConfig:
        - environment: prod
          monitoring: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
    - name: backend
      src: src/BackEnd
      ports:
        - name: http
          port: 5001
      environmentConfig:
        - environment: dev
          variables:
        - environment: prod
          replicas: 2
          variables:
      secrets:
        - SEPES_KEYVAULT_URL
        - SEPES_CLIENT_ID
        - SEPES_CLIENT_SECRET
  dnsAppAlias:
    environment: prod
    component: frontend
  dnsExternalAlias:
