name: API
on:
  repository_dispatch:
  pull_request:
    branches: 
      - master
      - develop
    paths:
      - src/Sepes.RestApi/*
      - .github/workflows/api.yml
      - Database/*
      - src/Dockerfile
      - tools/*
  push:
    paths:
      - src/Sepes.RestApi/*
      - .github/workflows/api.yml
      - Database/*
      - src/Dockerfile
      - tools/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Docker login
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_URL }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Builds the Sepes API
    - name: docker build
      run: |
        docker build src -t ${{ secrets.ACR_URL }}/sepes-api:latest
        docker push ${{ secrets.ACR_URL }}/sepes-api:latest