name: Combined coverage report
on:
  pull_request:    
    branches: [ master, develop ]  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
      azureSubscriptionId: 6cfb8f33-6d4b-43bf-9000-91fd6f53ca28
 
    steps:
    - uses: actions/checkout@v2   

    # generate coverage report
    - name: Build combined coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:src/Sepes.Tests/TestResults/**/coverage.cobertura.xml;src/Sepes.RestApi.IntegrationTests/TestResults/**/coverage.cobertura.xml -targetdir:${{github.workspace}}/CodeCoverage/Combined -reporttypes:HtmlSummary -title:"All Tests"

    # upload code coverage report as build artifact
    - name: Upload coverage report as build artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Combined Test Coverage Report'
        path: ${{github.workspace}}/CodeCoverage/Combined/summary.htm     
   