name: function app
on:
  repository_dispatch:
  pull_request:
    branches: 
      - master
      - develop
    paths:
      - src/Sepes.Functions/*
      - .github/workflows/function-app.yml
  push:
    paths:
      - src/Sepes.Functions/*
      - .github/workflows/function-app.yml
env:
  ciTag: ${{ secrets.ACR_URL }}/function-app/ci
  prodTag: ${{ secrets.ACR_URL }}/function-app/prod
  acr: ${{ secrets.ACR_URL }}/

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    env:
        environment: CI
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Docker login
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Builds the function app
      - name: docker build
        run: |
          docker build src -f src/Sepes.Functions/Dockerfile -t ${{ env.ciTag }}:latest
          docker push ${{ env.ciTag }}
          # removed  -t ${{ env.ciTag }}:$GITHUB_RUN_ID

  prod:
    if: github.ref == 'refs/heads/functionrun'
    runs-on: ubuntu-latest
    env:
        environment: prod
        azureSubscriptionId: 87f8c7ae-703b-4975-8a05-be359583c563
        runner: "testing variable"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Docker login
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Builds the function app
      - name: docker build
        run: |
          docker build src -f src/Sepes.Functions/Dockerfile -t ${{ env.acr }}${{ env.environment }}:$GITHUB_RUN_ID -t ${{ env.acr }}${{ env.environment }}:latest
          docker push ${{ env.acr }}${{ env.environment }}

      - name: Install modules
        shell: pwsh
        run: |
          Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force

      - name: Azure login
        shell: pwsh
        env:
          clientId: ${{ secrets.PROD_AZURE_CREDENTIALS_CLIENT_ID }}
          clientSecret:  ${{ secrets.PROD_AZURE_CREDENTIALS_CLIENT_SECRET }}
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          $azurePassword = ConvertTo-SecureString "$Env:clientSecret" -AsPlainText -Force
          $psCred = New-Object System.Management.Automation.PSCredential($Env:clientId , $azurePassword)
          Add-azAccount -Credential $psCred -TenantId $Env:tenantId -ServicePrincipal
          az login --service-principal -u $Env:clientId --password "$Env:clientSecret" --tenant $Env:tenantId
          az account set -s ${{ env.azureSubscriptionId }}
          Set-AzContext -SubscriptionId ${{ env.azureSubscriptionId }}

      - name: Deploy Function
        shell: pwsh
        env:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          githubId: ${{ env.GITHUB_RUN_ID }}
        run: |
          Import-Module .\.github\scripts\powershell-modules\FunctionApp\FunctionApp.psm1
          $container = [System.String]::Concat("${{ env.acr }}", "${{ env.environment }}", ":", "$Env:githubId")
          Update-FunctionAppContainerSettings -FunctionName func-sepes-prod `
            -RgName rg-sepes-prod `
            -ImageName "$container" `
            -RegistryUsername "$Env:username" `
            -RegistryPassord "$Env:password" `
            -RegistryUrl "${{ env.acr }}"

      - name: Azure logout
        shell: pwsh
        run: |
          az logout
          LogOut-AzAccount

      - name: runId
        env:
          id: ${{ env.GITHUB_RUN_ID }}
        shell: pwsh
        run: |
          #echo $GITHUB_RUN_ID
          #echo ${{ env.GITHUB_RUN_ID }}
          #echo $id
          echo $Env:id
          echo $GITHUB_WORKFLOW
          echo ${{ env.runner }}