name: Unit Tests
on:
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
      
      # restore dependencies  
    - name: Install dependencies
      working-directory: src/Sepes.Tests
      run: dotnet restore
      
      # build project
    - name: Build
      working-directory: src/Sepes.Tests
      run: dotnet build --configuration $config --no-restore
      
    - name: set pr build number (if pr)
      id: PRNUMBER
      if: ${{ github.event_name == 'pull_request' }}
      uses: kkak10/pr-number-action@v1.3
      
      # set report file and title 
    - name: Set Test Title
      run: | 
            if ${{ github.event_name == 'pull_request' }}
            then
              echo "::set-env name=title::Test Run for PR #${{steps.PRNUMBER.outputs.pr}} (${{github.run_number}})"
              echo "::set-env name=file_name::TestReport.${{steps.PRNUMBER.outputs.pr}}.${{github.run_number}}.md"
            else
              echo "::set-env name=title::Test Run ${{github.run_number}}"
              echo "::set-env name=file_name::TestReport.${{github.run_number}}.md"
            fi
      
      # run tests with built project
    - name: Test PR
      working-directory: src/Sepes.Tests    
      run: dotnet test --no-restore --no-build --configuration $config --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
      
      - name: runecho
      env:
        ZEH_PATH: ${{env.file_name}}
      run: echo "$ZEH_PATH"

      # upload report as build artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Test Run'
        path: ${{github.workspace}}/${{env.file_name}}


      
      # add report as PR comment (if PR)
    - name: Add PR comment
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: ${{env.file_name}}